### ISSUE TITLE
Struggling to find right parameters?

### ISSUE THREAD

**Issue by Zera97** [du-lab/nonnegative_matrix_factorization#1]
Hello,
i wanted to factorize the following 5x5 matrix(with k = 2) using this library:

1,0000E+00   1,0000E+00   0,0000E+00   0,0000E+00   0,0000E+00 
0,0000E+00   0,0000E+00   1,0000E+00   0,0000E+00   0,0000E+00 
1,0000E+00   1,0000E+00   0,0000E+00   1,0000E+00   0,0000E+00 
0,0000E+00   0,0000E+00   1,0000E+00   1,0000E+00   0,0000E+00 
0,0000E+00   0,0000E+00   0,0000E+00   0,0000E+00   1,0000E+00 

As one of the resulting matrices i expect a 2 x 5 matrix for example:
0,0000E+00   0,0000E+00   1,0000E+00   1,0000E+00   0,0000E+00
1,0000E+00   1,0000E+00   0,0000E+00   1,0000E+00   1,0000E+00

But the matrix (matrixH) i get is the following:
 0,0000E+00  0,0000E+00  0,0000E+00  0,0000E+00  0,0000E+00 
-0,0000E+00 -0,0000E+00  0,0000E+00  0,0000E+00 -0,0000E+00 

Im using the following code from your example:
`new SingularValueDecomposition(matrixX).decompose(matrixW, matrixH); ` 
`UpdateRule updateRuleW = new MUpdateRule(1.0, 0.0);`
`UpdateRule updateRuleH = new MUpdateRule(0.0, 1.0);`
`new MatrixFactorization(updateRuleW, updateRuleH, 1e-4, 10000).execute(matrixX, matrixW,matrixH); `

I tried to change the rules,tolerance and iterations(like in the unit test) but i still dont get a matrix which is close enough to the desired matrix. Maybe you can help me adjusting the parameters so the resulting matrices are closer to the desired matrices?

**Comment by asmirn1** [comment]
Hi @Zera97 

I'll be glad to help you with these parameters. In this case, the regularization parameters `lambda` and `mu` are too high. You can try to set them to zero as follows
```java
UpdateRule updateRuleW = new MUpdateRule(0.0, 0.0);
UpdateRule updateRuleH = new MUpdateRule(0.0, 0.0);
```
or some small values like 0.001.

I ran it with zero regularization parameters and got non-zero W and H matrices.

**Comment by Zera97** [comment]
Hi @asmirn1,

thank you very much, working like a charm!
